-- Script to initialize (or reset) the database
-- all SCHEMAs, TABLEs and other objects are dropped
-- and SCHEMAs are created and authorized

--DROP SCHEMA IF EXISTS "DATAVAULT_CONTROLLING" CASCADE;
--CREATE SCHEMA "DATAVAULT_CONTROLLING";

--GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "DATAVAULT_CONTROLLING" TO controlling_admins;
--GRANT SELECT ON ALL TABLES IN SCHEMA "DATAVAULT_CONTROLLING" TO controlling_users;

DROP SCHEMA IF EXISTS "DATAVAULT" CASCADE;
CREATE SCHEMA "DATAVAULT";

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "DATAVAULT" TO dwh_admins;
GRANT SELECT ON ALL TABLES IN SCHEMA "DATAVAULT" TO dwh_users;

DROP SCHEMA IF EXISTS "DATAVAULT_PSA" CASCADE;
CREATE SCHEMA "DATAVAULT_PSA";

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "DATAVAULT_PSA" TO dwh_admins;

DROP SCHEMA IF EXISTS "SALES" CASCADE;
CREATE SCHEMA SALES;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "SALES" TO dwh_admins;
GRANT SELECT ON ALL TABLES IN SCHEMA "SALES" TO sales_users;


--
